-- Create distress_messages table
CREATE TABLE public.distress_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  contact text,
  location text,
  message text,
  severity smallint CHECK (severity >= 1 AND severity <= 5),
  created_at timestamp with time zone DEFAULT now()
);

-- Create missing_persons table
CREATE TABLE public.missing_persons (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name text,
  age int,
  gender text,
  description text,
  last_seen text,
  contact text,
  photo_url text,
  created_at timestamp with time zone DEFAULT now()
);

-- Create subscribers table
CREATE TABLE public.subscribers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text UNIQUE,
  created_at timestamp with time zone DEFAULT now()
);

-- Enable RLS on all tables
ALTER TABLE public.distress_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.missing_persons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscribers ENABLE ROW LEVEL SECURITY;

-- Create policies to allow public inserts and reads (no auth required)
CREATE POLICY "Allow public insert on distress_messages"
  ON public.distress_messages
  FOR INSERT
  TO public
  WITH CHECK (true);

CREATE POLICY "Allow public read on distress_messages"
  ON public.distress_messages
  FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Allow public insert on missing_persons"
  ON public.missing_persons
  FOR INSERT
  TO public
  WITH CHECK (true);

CREATE POLICY "Allow public read on missing_persons"
  ON public.missing_persons
  FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Allow public insert on subscribers"
  ON public.subscribers
  FOR INSERT
  TO public
  WITH CHECK (true);

-- Create storage bucket for missing person photos
INSERT INTO storage.buckets (id, name, public)
VALUES ('missing-persons', 'missing-persons', true);

-- Create storage policies for public access
CREATE POLICY "Allow public uploads to missing-persons bucket"
  ON storage.objects
  FOR INSERT
  TO public
  WITH CHECK (bucket_id = 'missing-persons');

CREATE POLICY "Allow public read from missing-persons bucket"
  ON storage.objects
  FOR SELECT
  TO public
  USING (bucket_id = 'missing-persons');